#ifndef GENERAL_CONFIG_H
#define GENERAL_CONFIG_H
#include <ArduinoLog.h>

// Available levels are:
// LOG_LEVEL_SILENT, LOG_LEVEL_FATAL, LOG_LEVEL_ERROR, LOG_LEVEL_WARNING, LOG_LEVEL_INFO, LOG_LEVEL_TRACE, LOG_LEVEL_VERBOSE
#define LOG_LEVEL LOG_LEVEL_TRACE

#endif // GENERAL_CONFIG_H